# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [121]:
import numpy as np
info=np.loadtxt("minutes_n_ingredients.csv", dtype=str, delimiter=',')
massiv=np.array(info[1:],dtype=np.int32)
print(massiv[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [145]:
masno1=massiv[:,1]
masno2=massiv[:,2]
print(np.average(masno1),np.average(masno2),np.min(masno1),np.min(masno2),np.max(masno1),np.max(masno2))

21601.00648 9.05528 1 1 2147483647 39


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [123]:
np.quantile(masno2,0.75)

11.0

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [124]:
print(sum(masno1==0))
np.place(masno1,masno1==0,1)

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [125]:
len(np.unique(massiv))

100544

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [130]:
print(len(np.unique(masno2)))
np.unique(masno2)

37


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 37, 39])

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [142]:
massiv[masno2<=5]


array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [144]:
print(masno2/masno1)
np.max(masno2/masno1)

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]


24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [148]:
np.average(massiv[np.argsort(masno1)][-100:,2])

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [163]:
import random
def rand():
    print(massiv[random.randint(0,100002)])
for i in range(10):
    rand()

[457235      5      9]
[290433     50      8]
[61412    30     8]
[157221     10     13]
[410258     35      8]
[373439    260     14]
[473512    435     13]
[189225     15      9]
[154187     30      4]
[68375    55    12]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [182]:
d=len(massiv[masno2<np.average(masno2)][:,2]/len(masno2))
d/1000

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

In [187]:
z=massiv[masno1<=20]
len(z[z[:,2]<=5])*100/len(massiv)

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.